# Generated by Django 5.2.1 on 2025-05-25 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupilheart', '0002_hrvdb_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='newhrvdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_1', models.FloatField()),
                ('pupil_2', models.FloatField()),
                ('pupil_3', models.FloatField()),
                ('pupil_4', models.FloatField()),
                ('pupil_5', models.FloatField()),
                ('pupil_6', models.FloatField()),
                ('pupil_7', models.FloatField()),
                ('pupil_8', models.FloatField()),
                ('pupil_9', models.FloatField()),
                ('pupil_10', models.FloatField()),
                ('pupil_11', models.FloatField()),
                ('pupil_12', models.FloatField()),
                ('pupil_13', models.FloatField()),
                ('pupil_14', models.FloatField()),
                ('pupil_15', models.FloatField()),
                ('pupil_16', models.FloatField()),
                ('pupil_17', models.FloatField()),
                ('pupil_18', models.FloatField()),
                ('pupil_19', models.FloatField()),
                ('pupil_20', models.FloatField()),
                ('pupil_21', models.FloatField()),
                ('pupil_22', models.FloatField()),
                ('pupil_23', models.FloatField()),
                ('pupil_24', models.FloatField()),
                ('pupil_25', models.FloatField()),
                ('pupil_26', models.FloatField()),
                ('pupil_27', models.FloatField()),
                ('pupil_28', models.FloatField()),
                ('pupil_29', models.FloatField()),
                ('pupil_30', models.FloatField()),
                ('pupil_31', models.FloatField()),
                ('pupil_32', models.FloatField()),
                ('pupil_33', models.FloatField()),
                ('pupil_34', models.FloatField()),
                ('pupil_35', models.FloatField()),
                ('pupil_36', models.FloatField()),
                ('pupil_37', models.FloatField()),
                ('pupil_38', models.FloatField()),
                ('pupil_39', models.FloatField()),
                ('pupil_40', models.FloatField()),
                ('pupil_41', models.FloatField()),
                ('pupil_42', models.FloatField()),
                ('pupil_43', models.FloatField()),
                ('pupil_44', models.FloatField()),
                ('pupil_45', models.FloatField()),
                ('pupil_46', models.FloatField()),
                ('pupil_47', models.FloatField()),
                ('pupil_48', models.FloatField()),
                ('pupil_49', models.FloatField()),
                ('pupil_50', models.FloatField()),
                ('pupil_51', models.FloatField()),
                ('pupil_52', models.FloatField()),
                ('pupil_53', models.FloatField()),
                ('pupil_54', models.FloatField()),
                ('pupil_55', models.FloatField()),
                ('pupil_56', models.FloatField()),
                ('pupil_57', models.FloatField()),
                ('pupil_58', models.FloatField()),
                ('pupil_59', models.FloatField()),
                ('pupil_60', models.FloatField()),
                ('hrv_prediction', models.FloatField()),
                ('hrv_detection_type', models.CharField(choices=[('Low', 'Low Variability'), ('Normal', 'Normal Variability'), ('High', 'High Variability')], default='Low', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hrvdb',
        ),
    ]
