# Generated by Django 5.2.1 on 2025-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupilheart', '0003_newhrvdb_delete_hrvdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaddataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('file', models.FileField(upload_to='datasets/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
