# Generated by Django 5.2.1 on 2025-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupilheart', '0004_uploaddataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
